# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb7ece9ba972589adc42f6de0fcd70bcd9745c4d891a022f0f6a2ea7b1306fb52ec87edf7ee706caaa59ebbcd9538b65e4b52cf68697c12a6eb91b891be8e0f

test:
  secret_key_base: 6a2530e2c64bce0bd529ce46a7b32efd2b09289cda7f0657ce7aa7c56800eca5627ade7b0a652acc6e97f61fae89ead5c8db89190ebe77e75642b0c8042a37a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
